# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
package_manager_aliases_file:
  RedHat: dnf-aliases.txt
  Debian: apt-aliases.txt
  Archlinux: pacman-aliases.txt
  Suse: zypper-aliases.txt
