---
- hosts: all

  tasks:
    - name: Get Ubuntu codename
      set_fact:
        ubuntu_codename: "{{ 'impish' if ansible_lsb.description is search('development branch', ignorecase=True) else ansible_distribution_release }}"

    - name: dbg
      ansible.builtin.debug:
        msg: "Ubuntu codename {{ ubuntu_codename }}, {{ ansible_lsb.description }}, {{ ansible_distribution_release }}"
