# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/debug"
    schedule:
      interval: "weekly"
