Vagrant.configure(2) do |config|

  vm_name = 'system-automation-fedora'

  config.vm.box = "box-cutter/fedora24"
  config.vm.hostname = vm_name

  config.vm.provider 'virtualbox' do |provider|
    provider.memory = 1024
    provider.cpus = 2
    provider.name = vm_name
  end

  config.vm.provision "shell", inline: "dnf install --assumeyes python python-dnf"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../system-automation.yml"
      ansible.raw_arguments = [
          '--verbose'
      ]
  end
end
