# SPDX-FileCopyrightText: 2022 Maxwell G <gotmax@e.email>
# SPDX-License-Identifier: Unlicense
---
- name: Enable EPEL repositories on RHEL and derivatives
  become: true
  when:
    - "ansible_facts['os_family'] == 'RedHat'"
    - "ansible_facts['distribution'] != 'Fedora'"
  block:
    - name: Enable EPEL
      ansible.builtin.include_role:
        name: gotmax23.epel.epel

    - name: Enable EPEL Next
      when:
        - "ansible_facts['distribution'] == 'CentOS'"
        - "ansible_facts['distribution_release'] == 'Stream'"
      ansible.builtin.include_role:
        name: gotmax23.epel.epel_next

    - name: Enable CRB
      when: ansible_facts['distribution_major_version'] | int >= 8
      ansible.builtin.include_role:
        name: gotmax23.epel.crb
