---
- hosts: all
  name: Common Playbook

  vars_files:
    - [default.config.yml, config.yml]

  roles:
    - basic
    - dotfiles
    - bin
    - directories
    - virtualization
    - docker
    - c
