# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Common Playbook
  hosts: all

  vars_files:
    - [default.config.yml, config.yml]

  roles:
    - basic
    - dotfiles
    - bin
    - directories
    - docker
    - development
    - virtualization
