username: florian

basic_packages:
  Debian:
    - apg
    - asciidoctor
    - autojump
    - backblaze-b2
    - build-essential
    - curl
    - direnv
    - git
    - htop
    - httpie
    - iotop
    - jq
    - make
    - mc
    - pandoc
    - python-is-python3
    - python3
    - rdiff-backup
    - silversearcher-ag
    - texlive-latex-recommended
    - tree
    - unzip
    - vim
    - zsh
  RedHat:
    - apg
    - autojump
    - autojump-zsh
    - curl
    - direnv
    - git
    - htop
    - httpie
    - jq
    - make
    - mc
    - rdiff-backup
    - the_silver_searcher
    - tree
    - unzip
    - vim
    - xz
    - zsh

desktop_packages:
  Debian:
    - "keepassxc"
    - "xclip"
  RedHat:
    - "firefox"
    - "keepassxc"
    - "libreoffice"
    - "libreoffice-langpack-de"
    - "xclip"

system_development_packages:
  Debian:
    - build-essential
    - cmake
  RedHat:
    - "@C Development Tools and Libraries"
    - cmake

JDK_VERSION: "11.0.11"
MAVEN_VERSION: "3.8.1"
GRADLE_VERSION: "7.0"
ANT_VERSION: "1.10.9"
NODE_VERSION: "14.16.1"
GO_VERSION: "1.16.3"
GH_VERSION: "1.9.1"
KOTLIN_VERSION: "1.4.32"
TOPGRADE_VERSION: "v6.9.0"

development_tools:
  linux:
    - "https://github.com/SAP/SapMachine/releases/download/sapmachine-{{ JDK_VERSION }}/sapmachine-jdk-{{ JDK_VERSION }}_linux-x64_bin.tar.gz"
    - "https://mirror.netcologne.de/apache.org/maven/maven-3/{{ MAVEN_VERSION }}/binaries/apache-maven-{{ MAVEN_VERSION }}-bin.tar.gz"
    - "https://downloads.gradle-dn.com/distributions/gradle-{{ GRADLE_VERSION }}-bin.zip"
    - "https://nodejs.org/dist/v{{ NODE_VERSION }}/node-v{{ NODE_VERSION }}-linux-x64.tar.xz"
    - "https://golang.org/dl/go{{ GO_VERSION }}.linux-amd64.tar.gz"
    - "https://ftp.halifax.rwth-aachen.de/apache//ant/binaries/apache-ant-{{ ANT_VERSION }}-bin.tar.xz"
    - "https://github.com/cli/cli/releases/download/v{{ GH_VERSION }}/gh_{{ GH_VERSION }}_linux_amd64.tar.gz"
    - "https://github.com/JetBrains/kotlin/releases/download/v{{ KOTLIN_VERSION }}/kotlin-compiler-{{ KOTLIN_VERSION }}.zip"
    - "https://github.com/JetBrains/kotlin/releases/download/v{{ KOTLIN_VERSION }}/kotlin-native-linux-{{ KOTLIN_VERSION }}.tar.gz"

directories:
  - "~/temp"
  - "~/code"
  - "~/no_backup"

codium_extensions:
  - fwcd.kotlin
  - golang.go
  - humao.rest-client
  - mathiasfrohlich.Kotlin
  - ms-azuretools.vscode-docker
  - ms-python.python
  - redhat.java
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - rust-lang.rust
  - streetsidesoftware.code-spell-checker
