username: florian

basic_packages:
  Debian:
    - apg
    - curl
    - git
    - htop
    - httpie
    - jq
    - make
    - mc
    - python-is-python3
    - python3
    - rdiff-backup
    - silversearcher-ag
    - unzip
    - vim
    - zsh
    - net-tools
    - bridge-utils
  RedHat:
    - apg
    - curl
    - git
    - htop
    - httpie
    - jq
    - make
    - mc
    - rdiff-backup
    - the_silver_searcher
    - unzip
    - vim
    - xz
    - zsh
    - net-tools
    - bridge-utils
  Suse:
    - apg
    - bzip2
    - curl
    - git
    - gzip
    - htop
    - httpie
    - jq
    - make
    - mc
    - rdiff-backup
    - tar
    - the_silver_searcher
    - unzip
    - vim
    - xz
    - zsh
  Archlinux:
    - bzip2
    - curl
    - git
    - gzip
    - htop
    - httpie
    - jq
    - make
    - mc
    - rdiff-backup
    - tar
    - the_silver_searcher
    - unzip
    - vim
    - xz
    - zsh

desktop_packages:
  Debian:
    - "keepassxc"
    - "libreoffice-help-de"
    - "libreoffice-l10n-de"
    - "libreoffice"
    - "xclip"
  RedHat:
    - "firefox"
    - "keepassxc"
    - "libreoffice"
    - "libreoffice-langpack-de"
    - "xclip"

development_packages:
  Debian:
    - cargo
    - golang
    - maven
    - nodejs
    - npm
    - openjdk-17-jdk-headless
  RedHat:
    - cargo
    - golang
    - java-17-openjdk-devel
    - maven
    - nodejs
    - npm
    - rust
  Suse:
    - cargo
    - go
    - java-17-openjdk-devel
    - maven
    - nodejs-default
    - npm-default
    - rust
  Archlinux:
    - go
    - jdk-openjdk
    - maven
    - nodejs
    - npm
    - rust

system_development_packages:
  Debian:
    - build-essential
    - cmake
  RedHat:
    - "@C Development Tools and Libraries"
    - cmake

development_tools:
  linux:
    - "https://github.com/SAP/SapMachine/releases/download/sapmachine-{{ JDK_VERSION }}/sapmachine-jdk-{{ JDK_VERSION }}_linux-x64_bin.tar.gz"
    - "https://dlcdn.apache.org/maven/maven-3/{{ MAVEN_VERSION }}/binaries/apache-maven-{{ MAVEN_VERSION }}-bin.tar.gz"
    - "https://downloads.gradle-dn.com/distributions/gradle-{{ GRADLE_VERSION }}-bin.zip"
    - "https://nodejs.org/dist/v{{ NODE_VERSION }}/node-v{{ NODE_VERSION }}-linux-x64.tar.xz"
    - "https://golang.org/dl/go{{ GO_VERSION }}.linux-amd64.tar.gz"
    - "https://github.com/cli/cli/releases/download/v{{ GH_VERSION }}/gh_{{ GH_VERSION }}_linux_amd64.tar.gz"
    - "https://github.com/JetBrains/kotlin/releases/download/v{{ KOTLIN_VERSION }}/kotlin-compiler-{{ KOTLIN_VERSION }}.zip"
    - "https://github.com/JetBrains/kotlin/releases/download/v{{ KOTLIN_VERSION }}/kotlin-native-linux-x86_64-{{ KOTLIN_VERSION }}.tar.gz"

directories:
  - "~/temp"
  - "~/code"
  - "~/no_backup"

codium_extensions:
  - fwcd.kotlin
  - golang.go
  - humao.rest-client
  - mathiasfrohlich.Kotlin
  - ms-azuretools.vscode-docker
  - ms-python.python
  - redhat.java
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - rust-lang.rust
  - streetsidesoftware.code-spell-checker
