# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

username: florian

basic_packages:
  Debian:
    - apg
    - curl
    - git
    - htop
    - httpie
    - jq
    - make
    - mc
    - nala
    - python-is-python3
    - python3
    - rdiff-backup
    - silversearcher-ag
    - tealdeer
    - unzip
    - vim
    - yapf3
    - zsh
    - net-tools
    - bridge-utils
  RedHat:
    - apg
    - curl
    - git
    - htop
    - httpie
    - jq
    - make
    - mc
    - rdiff-backup
    - the_silver_searcher
    - tldr
    - unzip
    - vim
    - xz
    - zsh
    - net-tools
    - bridge-utils
    - bzip2
  Suse:
    - apg
    - bzip2
    - curl
    - git
    - gzip
    - htop
    - httpie
    - jq
    - make
    - mc
    - rdiff-backup
    - tar
    - unzip
    - vim
    - xz
    - zsh
  Archlinux:
    - bzip2
    - curl
    - git
    - gzip
    - htop
    - httpie
    - jq
    - make
    - mc
    - tar
    - the_silver_searcher
    - unzip
    - vim
    - xz
    - zsh

desktop_packages:
  Debian:
    - "keepassxc"
    - "libreoffice-help-de"
    - "libreoffice-l10n-de"
    - "libreoffice"
    - "xclip"
  RedHat:
    - "firefox"
    - "keepassxc"
    - "libreoffice"
    - "libreoffice-langpack-de"
    - "xclip"

development_packages:
  Debian:
    - cargo
    - golang
    - maven
    - nodejs
    - npm
    - yarnpkg
    - default-jdk-headless
  RedHat:
    - cargo
    - golang
    - java-21-openjdk-devel
    - maven
    - nodejs
    - npm
    - rust
  Suse:
    - cargo
    - go
    - java-21-openjdk-devel
    - maven
    - nodejs-default
    - npm-default
    - rust
  Archlinux:
    - go
    - jdk-openjdk
    - maven
    - nodejs
    - npm
    - rust

system_development_packages:
  Debian:
    - build-essential
    - cmake
  RedHat:
    - "@C Development Tools and Libraries"
    - cmake

homeserver_packages:
  Debian:
    - cockpit
    - cockpit-machines
    - cockpit-networkmanager
    - cockpit-packagekit
    - cockpit-podman
    - cockpit-storaged
    - cockpit-system
    - cockpit-ws
  RedHat:
    - cockpit
    - cockpit-machines
    - cockpit-podman
    - cockpit-files

directories:
  - "~/temp"
  - "~/code"
  - "~/code/scratch"
  - "~/code/fwilhe2"
  - "~/no_backup"

codium_extensions:
  - fwcd.kotlin
  - golang.go
  - humao.rest-client
  - mathiasfrohlich.Kotlin
  - ms-azuretools.vscode-docker
  - ms-python.python
  - redhat.java
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - rust-lang.rust
  - streetsidesoftware.code-spell-checker
