---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: greenleader.codium
      become: true

  tasks:

  - name: Install Desktop Packages
    become: true
    become_user: root
    package:
      state: present
      name: "{{ item.name | default(item) }}"
    loop: "{{ desktop_packages[ansible_os_family] }}"

    - name: Install VS Codium Extensions
      codium-extensions:
        name: "{{ item }}"
        state: present
      with_items:
        - fwcd.kotlin
        - golang.go
        - humao.rest-client
        - mathiasfrohlich.Kotlin
        - ms-azuretools.vscode-docker
        - ms-python.python
        - redhat.java
        - redhat.vscode-xml
        - redhat.vscode-yaml
        - rust-lang.rust
        - streetsidesoftware.code-spell-checker
