---

- hosts: all

  roles:
    - { role: greenleader.codium, become: yes }

  tasks:
    - name: Install Basic Desktop Packages
      become: yes
      dnf:
        state: latest
        name: ['keepassxc', 'libreoffice-langpack-de', 'xclip']
      when: ansible_os_family == 'RedHat'

    - name: Install Basic Desktop Packages
      become: yes
      apt:
        state: latest
        name: ['keepassxc', 'xclip']
      when: ansible_os_family == 'Debian'

    - name: Install VS Codium Extensions
      codium-extensions:
        name: "{{ item }}"
        state: present
      with_items:
        - fwcd.kotlin
        - golang.go
        - mathiasfrohlich.Kotlin
        - ms-azuretools.vscode-docker
        - ms-python.python
        - redhat.java
        - redhat.vscode-xml
        - rust-lang.rust
        - streetsidesoftware.code-spell-checker
      tags:
        - notest