# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- hosts: all
  name: Desktop (GNOME) Playbook

  vars_files:
    - default.config.yml

  roles:
    - role: greenleader.codium
      become: true

    - role: flatpak

    - role: rpm-fusion
      become: true

  tasks:
    - name: Install Desktop Packages
      become: true
      become_user: root
      ansible.builtin.package:
        state: present
        name: "{{ item }}"
      loop: "{{ desktop_packages[ansible_os_family] }}"

    - name: Install VS Codium Extensions
      codium-extensions:
        name: "{{ item }}"
        state: present
      loop: "{{ codium_extensions }}"
