---

- hosts: all
  tasks:
    - name: Install Basic Desktop Packages
      become: yes
      dnf:
        state: latest
        name: ['keepassxc', 'libreoffice-langpack-de', 'xclip']
      when: ansible_os_family == 'RedHat'

    - name: Install Basic Desktop Packages
      become: yes
      apt:
        state: latest
        name: ['keepassxc', 'xclip']
      when: ansible_os_family == 'Debian'


