# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Development environment (vm guest)
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load Configuration Overrides
      ansible.builtin.include_vars: "{{ item }}"
      loop: "{{ query('ansible.builtin.first_found', ['config.yml'], errors='ignore') }}"
      tags: always

  roles:
    - basic
    - dotfiles
    - bin
    - directories
    - docker
    - development
