# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- hosts: all
  name: Minimal Playbook

  vars_files:
    - [default.config.yml, config.yml]

  roles:
    - basic
    - dotfiles
    - directories
    - docker
