= system-automation
:experimental: yes
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

image::https://github.com/fwilhe2/system-automation/workflows/CI/badge.svg[CI Job]

System Automation powered by Ansible™

Tested ansible version:

----
ansible 2.9.18
----

== Project Layout

* `common.yml`: Software that does not require a graphical environment.
* `desktop.yml`: Setup for desktop computers.

== Preparation

.Preparation for Fedora
----
sudo dnf install -y ansible curl bash unzip
----

.Preparation for Ubuntu
----
sudo apt -y install ansible curl bash unzip
----

== Kickstart (experimental)

If you don't mind the `curl | bash` thing, you might try running the playbook directly via:

----
curl https://raw.githubusercontent.com/fwilhe2/system-automation/master/bootstrap.sh | bash
----

This requires `ansible`, `curl`, `bash` and `unzip`.

== Setup (traditional)

.Run `common` playbook
----
ansible-playbook --ask-become-pass --inventory inventory common.yml
----

.Run `desktop` playbook
----
ansible-playbook --ask-become-pass --inventory inventory desktop.yml
----

WARNING: Running the `desktop` playbook will override the custom keybindings in GNOME. kbd:[Ctrl+Alt+T] is set to open a new `gnome-terminal`.

== Testing

Vagrant can be used to test this project.

Various Vagrantfiles are provided in the `test` directory.

.Fire up Vagrant VM with Ansible Provisioning
----
vagrant up
----

.Provision running VM
----
vagrant provision
----

== License

Copyright © 2016 Florian Wilhelm

Free use of this software is granted under the terms of the MIT License.

=== Copyright Notice

This project ships the following 3rd party software:

https://github.com/jistr/ansible-gsetting[ansible-gsetting module] (`playbooks/library/gsetting`)::
  Copyright © Jiří Stránský under the _Apache License, Version 2.0_

== References

* https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html[Ansible Docs: All Modules]
* http://www.whitewashing.de/2013/11/19/setting_up_development_machines_ansible_edition.html[Setting up development machines: Ansible edition]
