= system-automation
:experimental: yes
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

image::https://github.com/fwilhe2/system-automation/workflows/CI/badge.svg[CI Job]

System Automation powered by Ansible™

== Project Layout

This project contains two playbooks:

* `common.yml`: Software and setup which does not require a graphical environment
* `desktop.yml`: Setup for desktop computers

== Preparation

.Preparation for Fedora/*EL-like
----
sudo dnf install -y ansible-core curl bash unzip
----

.Preparation for Ubuntu/Debian
----
sudo apt -y install ansible curl bash unzip
----

.Preparation for Archlinux
----
sudo pacman --sync --refresh --noconfirm ansible curl bash unzip git
----

== Kickstart (experimental)

If you don't mind the `curl | bash` thing, you might try running the playbook directly via:

----
curl https://raw.githubusercontent.com/fwilhe2/system-automation/main/bootstrap.sh | bash
----

This requires `ansible`, `curl`, `bash` and `unzip`.

== Setup (traditional)

.Run `common` playbook
----
ansible-playbook --ask-become-pass --inventory inventory common.yml
----

.Run `desktop` playbook
----
ansible-playbook --ask-become-pass --inventory inventory desktop.yml
----

== Testing

=== Containerfile

Containerfiles are available for testing.
They are run automatically via the CI workflow.

For running them locally, use:

.Test on Ubuntu
----
docker build --build-arg=VERSION=latest -t system-automation-test-ubuntu-latest --file test/container/Containerfile.ubuntu .
docker run --tty --volume $PWD:/mnt system-automation-test-ubuntu-latest
----

.Test on Fedora
----
docker build --build-arg=VERSION=latest -t system-automation-test-fedora-latest --file test/container/Containerfile.fedora .
docker run --tty --volume $PWD:/mnt system-automation-test-fedora-latest
----

=== Vagrantfile

Vagrantfiles with provider `libvirt` are available for testing.

.Setup on Fedora (on the host)
----
sudo dnf install libvirt vagrant vagrant-libvirt
----

.Change into any of the `Vagrantfile` directories and run
----
export VAGRANT_DEFAULT_PROVIDER=libvirt
vagrant up
----

== License

Copyright © 2016-2023 Florian Wilhelm

Free use of this software is granted under the terms of the MIT License.

=== Copyright Notice

This project ships the following 3rd party software:

https://github.com/green-leader/ansible-role-codium[ansible-role-codium] (`roles/greenleader.codium`)::
  Copyright © Sion Fandrick under the _MIT License_

https://github.com/gantsign/ansible-role-visual-studio-code-extensions[ansible-role-visual-studio-code-extensions] (`library/codium-extensions`)::
  Copyright © John Freeman GantSign Ltd. Company No. 06109112 (registered in England) under the _MIT License_

https://git.sr.ht/~gotmax23/ansible-collection-epel[Ansible collection - gotmax23.epel] (`roles/gotmax23.epel*`)::
  Copyright © 2022 Maxwell G (@gotmax23) under the _MIT License_

== References

* https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html[Ansible Docs: All Modules]
* http://www.whitewashing.de/2013/11/19/setting_up_development_machines_ansible_edition.html[Setting up development machines: Ansible edition]
* https://github.com/geerlingguy/mac-dev-playbook
* https://github.com/geerlingguy/ansible-role-docker
