= system-automation

System Automation powered by Ansible™

Tested ansible version: `2.0.1.0`

== Project Layout

* `playbooks/common.yml`: Setup for a (in my personal view) minimal system. Does not require an X server.
* `playbooks/desktop.yml`: Setup for desktop computers.

== Setup

Make sure that `python-dnf` is installed.

.Run `common` playbook
----
ansible-playbook -K -i inventory system-automation.yml
----

.Run `desktop` playbook
----
ansible-playbook -K -v -i inventory playbooks/desktop.yml
----

== Testing

Vagrant can be used to test this project.
This does not include the `desktop` playbook.

Various Vagrantfiles are provided in the `test` directory.

.Fire up Vagrant VM with Ansible Provisioning
----
vagrant up
----

.Provision running VM
----
vagrant provision
----

== License

Copyright © 2016 Florian Wilhelm

Free use of this software is granted under the terms of the MIT License.

=== Copyright Notice

This project ships the following 3rd party software:

https://github.com/jistr/ansible-gsetting[ansible-gsetting module] (`playbooks/library/gsetting`)::
  Copyright © Jiří Stránský under the _Apache License, Version 2.0_

== References

* http://docs.ansible.com/ansible/list_of_all_modules.html[Ansible Docs: All Modules]
* http://www.whitewashing.de/2013/11/19/setting_up_development_machines_ansible_edition.html[Setting up development machines: Ansible edition]
