= system-automation
:experimental: yes
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

System Automation powered by Ansible™

Tested ansible version:

----
ansible 2.6.5
----

== Project Layout

* `common.yml`: Setup for a (in my personal view) minimal system. Does not require an X server.
* `desktop.yml`: Setup for desktop computers.
* `software-development.yml`: Setup for a software development machine.

== Setup

.Preparations for Fedora
----
sudo dnf install ansible python-dnf libselinux-python
----

Install third party roles using `ansible-galaxy`:

----
ansible-galaxy install -r requirements.yml
----

.Run `common` playbook
----
ansible-playbook -K -i inventory common.yml
----

.Run `desktop` playbook
----
ansible-playbook -K -v -i inventory desktop.yml
----

WARNING: Running the `desktop` playbook will override the custom keybindings in GNOME. kbd:[Ctrl+Alt+T] is set to open a new `gnome-terminal`.

== Testing

Vagrant can be used to test this project.

Various Vagrantfiles are provided in the `test` directory.

.Fire up Vagrant VM with Ansible Provisioning
----
vagrant up
----

.Provision running VM
----
vagrant provision
----

== License

Copyright © 2016 Florian Wilhelm

Free use of this software is granted under the terms of the MIT License.

=== Copyright Notice

This project ships the following 3rd party software:

https://github.com/jistr/ansible-gsetting[ansible-gsetting module] (`playbooks/library/gsetting`)::
  Copyright © Jiří Stránský under the _Apache License, Version 2.0_

== References

* http://docs.ansible.com/ansible/list_of_all_modules.html[Ansible Docs: All Modules]
* http://www.whitewashing.de/2013/11/19/setting_up_development_machines_ansible_edition.html[Setting up development machines: Ansible edition]
