= system-automation
:experimental: yes
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

image::https://github.com/fwilhe2/system-automation/workflows/CI/badge.svg[CI Job]

System Automation powered by Ansible™

Tested ansible version:

----
ansible 2.9.18
----

== Project Layout

This project contains two playbooks:

* `common.yml`: Software and setup which does not require a graphical environment
* `desktop.yml`: Setup for desktop computers

== Preparation

.Preparation for Fedora
----
sudo dnf install -y ansible curl bash unzip
----

.Preparation for Ubuntu
----
sudo apt -y install ansible curl bash unzip
----

== Kickstart (experimental)

If you don't mind the `curl | bash` thing, you might try running the playbook directly via:

----
curl https://raw.githubusercontent.com/fwilhe2/system-automation/master/bootstrap.sh | bash
----

This requires `ansible`, `curl`, `bash` and `unzip`.

== Setup (traditional)

.Run `common` playbook
----
ansible-playbook --ask-become-pass --inventory inventory common.yml
----

.Run `desktop` playbook
----
ansible-playbook --ask-become-pass --inventory inventory desktop.yml
----

== Testing

Containerfiles are available for testing.
They are run automatically via the CI workflow.

For running them locally, use:

.Test on Ubuntu
----
docker build --build-arg=VERSION=latest -t system-automation-test-ubuntu-latest --file test/container/Containerfile.ubuntu .
docker run --tty --volume $PWD:/mnt system-automation-test-ubuntu-latest
----

.Test on Fedora
----
docker build --build-arg=VERSION=latest -t system-automation-test-fedora-latest --file test/container/Containerfile.fedora .
docker run --tty --volume $PWD:/mnt system-automation-test-fedora-latest
----

== License

Copyright © 2016-2021 Florian Wilhelm

Free use of this software is granted under the terms of the MIT License.

=== Copyright Notice

This project ships the following 3rd party software:

https://github.com/green-leader/ansible-role-codium[ansible-role-codium] (`roles/greenleader.codium`)::
  Copyright © Sion Fandrick under the _MIT License_

https://github.com/gantsign/ansible-role-visual-studio-code-extensions[ansible-role-visual-studio-code-extensions] (`library/codium-extensions`)::
  Copyright © John Freeman GantSign Ltd. Company No. 06109112 (registered in England) under the _MIT License_

== References

* https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html[Ansible Docs: All Modules]
* http://www.whitewashing.de/2013/11/19/setting_up_development_machines_ansible_edition.html[Setting up development machines: Ansible edition]
