# SPDX-FileCopyrightText: 2022 Maxwell G <gotmax@e.email>
# SPDX-License-Identifier: MIT
---
- when:
    - "ansible_os_family == 'RedHat'"
    - "ansible_distribution != 'Fedora'"
  block:
    - name: Enable EPEL
      ansible.builtin.include_role:
        name: gotmax23.epel.epel

    - name: Enable EPEL Next
      when:
        - "ansible_distribution == 'CentOS'"
        - "ansible_distribution_release == 'Stream'"
      ansible.builtin.include_role:
        name: gotmax23.epel.epel_next

    - name: Enable CRB
      when: ansible_distribution_major_version | int >= 8
      ansible.builtin.include_role:
        name: gotmax23.epel.crb
