Vagrant.configure(2) do |config|

  vm_name = 'system-automation-ubuntu'

  config.vm.box = "ubuntu/cosmic64"
  config.vm.hostname = vm_name

  config.vm.provider 'virtualbox' do |provider|
    provider.memory = 1024
    provider.cpus = 2
    provider.name = vm_name
  end

  config.vm.provision "shell", inline: "apt-get install -y python2; ln -fs /usr/bin/python2.7 /usr/bin/python"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../common.yml"
      ansible.raw_arguments = [
          '--verbose'
      ]
  end
end
