Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2110"

  config.vm.provider 'libvirt' do |provider|
    provider.memory = 2048
    provider.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../common.yml"
      ansible.raw_arguments = [
          '--verbose'
      ]
  end
end
