# SPDX-FileCopyrightText: 2022 Maxwell G <gotmax@e.email>
# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Enable CRB repository
    author:
      - Maxwell G <gotmax@e.email>
