ARG VERSION

FROM ubuntu:$VERSION

ENV TERM=xterm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  ansible \
  curl \
  bash \
  unzip \
  && mkdir -p /home/user && echo "user:x:1001:1001:user:/home/user:/bin/bash" >> /etc/passwd \
  && chown -R user /home/user

# Install Ansible inventory file.
# Taken from https://github.com/geerlingguy/docker-ubuntu1804-ansible/blob/97a8d76f87dc4a15e24c88214806448246fbfb98/Dockerfile#L37
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

COPY test/container/entrypoint.sh /entrypoint.sh

USER user

ENTRYPOINT ["/entrypoint.sh"]