ARG VERSION

FROM fedora:$VERSION

ENV TERM=xterm

RUN dnf --assumeyes update && dnf --assumeyes install git ansible curl unzip bash \
  && mkdir -p /home/user && echo "user:x:1001:1001:user:/home/user:/bin/bash" >> /etc/passwd \
  && chown -R user /home/user

# Install Ansible inventory file.
# Taken from https://github.com/geerlingguy/docker-fedora33-ansible/blob/bd54ebebc836c10e76938a7d52e2386b7f16960e/Dockerfile#L35
RUN mkdir -p /etc/ansible
RUN echo -e '[local]\nlocalhost ansible_connection=local ansible_become_password=toor123' > /etc/ansible/hosts

COPY . /home/user

RUN echo 'root:toor123' | chpasswd

USER user

ENTRYPOINT ["/home/user/entrypoint.sh"]