ARG VERSION

FROM fedora:$VERSION

ENV TERM=xterm

RUN dnf --assumeyes update && dnf --assumeyes install git ansible curl unzip bash sudo \
  && mkdir -p /home/user && echo "user:x:1001:1001:user:/home/user:/bin/bash" >> /etc/passwd \
  && chown -R user /home/user \
  echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers

# Install Ansible inventory file.
# Taken from https://github.com/geerlingguy/docker-fedora33-ansible/blob/bd54ebebc836c10e76938a7d52e2386b7f16960e/Dockerfile#L35
RUN mkdir -p /etc/ansible
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

COPY test/container/entrypoint.sh /entrypoint.sh

USER user

ENTRYPOINT ["/entrypoint.sh"]