ARG VERSION

FROM $VERSION

ENV TERM=xterm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  ansible \
  curl \
  bash \
  python3 \
  python3-pip \
  python3-distro \
  unzip \
  libasound2 \
  && mkdir -p /home/user \
  && echo "user:x:1001:1001:user:/home/user:/bin/bash" >> /etc/passwd \
  && echo "user:x:1001:" >> /etc/group \
  && chown -R user /home/user

# Install Ansible inventory file.
# Taken from https://github.com/geerlingguy/docker-ubuntu1804-ansible/blob/97a8d76f87dc4a15e24c88214806448246fbfb98/Dockerfile#L37
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local ansible_become_password=toor123" > /etc/ansible/hosts

RUN echo 'root:toor123' | chpasswd

USER user

COPY . /home/user

WORKDIR /home/user

ENTRYPOINT ["python3", "/home/user/test/container/run-test.py"]
