# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Install podman
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - podman
  become: true
