# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- import_tasks: dnf.yml
  tags:
    # Can't run in containers
    - notest
    - flatpak
  when: ansible_os_family == 'RedHat'
