---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install packages
  community.general.flatpak:
    method: user
    name:
      - com.google.Chrome
      - org.mozilla.firefox
      - org.videolan.VLC
