# SPDX-FileCopyrightText: 2022 Maxwell G (@gotmax23)
# SPDX-License-Identifier: MIT
---
- name: Install EPEL GPG Key
  ansible.builtin.rpm_key:
    key: "{{ epel_key }}"
    fingerprint: "{{ epel_key_fingerprint if
                     epel_verify_key_fingerprint else omit }}"

- name: Install EPEL repository
  ansible.builtin.package:
    name: "{{ epel_release_url }}"
