Vagrant.configure(2) do |config|
  config.vm.box = "generic/centos9s"

  config.vm.provider 'libvirt' do |provider|
    provider.memory = 1024
    provider.cpus = 2
  end

  config.vm.provider "virtualbox" do |provider|
    provider.memory = 1024
    provider.cpus = 2
  end

  config.vm.provision "shell", inline: "sudo dnf -y install ansible-core python3-dnf python3-libselinux"
  config.vm.provision "shell", inline: "ansible-galaxy collection install community.general", privileged: false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../epel.yml"
    ansible.raw_arguments = [
        '--verbose'
    ]
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../common.yml"
      ansible.raw_arguments = [
          '--verbose'
      ]
  end
end
