# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Install Locale Data
  ansible.builtin.package:
    state: present
    name: "{{ basic_locale_packages[ansible_facts['os_family']] }}"

- name: Generate Debian Locale
  community.general.locale_gen:
    name: "{{ basic_locale }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Enable Arch Locale
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^#?\\s*{{ basic_locale | regex_escape }}\\s+UTF-8$"
    line: "{{ basic_locale }} UTF-8"
  register: basic_arch_locale
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Generate Arch Locale
  ansible.builtin.command: locale-gen
  when:
    - ansible_facts['os_family'] == 'Archlinux'
    - basic_arch_locale.changed
  changed_when: true

- name: Configure Debian Locale
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: "^LANG="
    line: "LANG={{ basic_locale }}"
    create: true
    mode: "0644"
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure Red Hat and Arch Locale
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    regexp: "^LANG="
    line: "LANG={{ basic_locale }}"
    create: true
    mode: "0644"
  when: ansible_facts['os_family'] in ['RedHat', 'Archlinux']

- name: Configure openSUSE Locale
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/language
    regexp: "^RC_LANG="
    line: 'RC_LANG="{{ basic_locale }}"'
    create: true
    mode: "0644"
  when: ansible_facts['os_family'] == 'Suse'

- name: Install Basic Packages
  ansible.builtin.package:
    state: present
    name: >-
      {{ basic_packages[ansible_facts['distribution']]
      | default(basic_packages[ansible_facts['os_family']]) }}

- name: Set vim as default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure user
  ansible.builtin.user:
    name: "{{ username }}"
