---
- include: fedora.yml
  when: ansible_os_family == 'RedHat'
  tags: basic

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: basic

- name: Set vim as default editor
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim
  when: ansible_os_family == 'Debian'
  tags: basic
