# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Install Basic Packages
  ansible.builtin.package:
    state: present
    name: >-
      {{ basic_packages[ansible_facts['distribution']]
      | default(basic_packages[ansible_facts['os_family']]) }}

- name: Set vim as default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure user
  ansible.builtin.user:
    name: "{{ username }}"
