# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Install Development Packages
  ansible.builtin.package:
    state: present
    name: "{{ development_packages[ansible_facts['os_family']] }}"

- name: Install System Development Packages
  ansible.builtin.package:
    state: present
    name: >-
      {{ development_system_packages[ansible_facts['distribution']]
      | default(development_system_packages[ansible_facts['os_family']]) }}
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Install System Development Packages (Suse)
  community.general.zypper:
    state: present
    name: devel_basis
    type: pattern
  when: ansible_facts['os_family'] == 'Suse'
