---
- name: Install C Development Tools and Libraries
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - "@C Development Tools and Libraries"
      - cmake
  when: ansible_os_family == 'RedHat'
