---
- name: Install System Development Packages
  become: true
  become_user: root
  package:
    state: present
    name: "{{ item.name | default(item) }}"
  loop: "{{ system_development_packages[ansible_os_family] }}"
  tags: system_development
