---
# See:
# https://fedoramagazine.org/full-virtualization-system-on-fedora-workstation-30/

- name: Install the '@virtualization' package group
  dnf:
    name: "@virtualization"
    state: present
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'

- name: Install the '@Virtualization Host' package group
  dnf:
    name: "@Virtualization Host"
    state: present
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- name: Install Vagrant Packages
  become: true
  become_user: root
  ansible.builtin.package:
    state: present
    name: "{{ item }}"
  loop:
    - vagrant
    - vagrant-libvirt
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'

- name: Set the domain socket group ownership to libvirt
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_group = "libvirt"'
    line: 'unix_sock_group = "libvirt"'
  become: true
  when: ansible_os_family == 'RedHat'

- name: Adjust the UNIX socket permissions for the R/W socket
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms = "0770"'
    line: 'unix_sock_rw_perms = "0770"'
  become: true
  when: ansible_os_family == 'RedHat'

- name: Start and enable the libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: libvirt
    append: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: Add polkit rule for libvirt
  become: true
  copy:
    dest: /etc/polkit-1/rules.d/80-libvirt.rules
    content: |
      polkit.addRule(function(action, subject) {
        if (action.id == "org.libvirt.unix.manage" && subject.local && subject.active && subject.isInGroup("wheel")) {
          return polkit.Result.YES;
        }
      });
