---

# See:
# https://fedoramagazine.org/full-virtualization-system-on-fedora-workstation-30/

- name: Install the 'virtualization' package group
  dnf:
    name: '@virtualization'
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Set the domain socket group ownership to libvirt
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_group = "libvirt"'
    line: 'unix_sock_group = "libvirt"'
  become: true
  when: ansible_os_family == 'RedHat'

- name: Adjust the UNIX socket permissions for the R/W socket
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms = "0770"'
    line: 'unix_sock_rw_perms = "0770"'
  become: true
  when: ansible_os_family == 'RedHat'

- name: Start and enable the libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: libvirt
    append: yes
  become: true
  when: ansible_os_family == 'RedHat'



