# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Install Lima
  ansible.builtin.import_tasks: common.yml
  tags: virtualization

- name: Install Virtualization Packages
  become: true
  become_user: root
  ansible.builtin.package:
    state: present
    name: "{{ virtualization_packages[ansible_facts['distribution']] | default(virtualization_packages[ansible_facts['os_family']]) }}"
  tags: virtualization
