---
- name: Install Virtualization Packages
  become: true
  become_user: root
  package:
    state: present
    name: "{{ item }}"
  loop:
    - vagrant
    - vagrant-libvirt
    - virtinst
    - libvirt-bin
