---
- name: Install Virtualization Packages
  become: true
  become_user: root
  package:
    state: present
    name: "{{ item }}"
  loop:
    - libvirt-daemon
    - libvirt-daemon-system
    - qemu-system
    - vagrant
    - vagrant-libvirt
    - virtinst

- name: Start and enable the libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
  become: true

- name: Add user to the libvirt group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: libvirt
    append: yes
  become: true

- name: Edit libvirtd configuration file
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^(unix_sock_group\s*=\s*).*$'
    replace: '\1"libvirt"'
    backup: yes
  become: true

- name: Set UNIX socket permissions for the R/W socket
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^(unix_sock_rw_perms\s*=\s*).*$'
    replace: '\10770'
    backup: yes
  become: true
