# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
- name: Install RPM Fusion Packages
  become: true
  become_user: root
  ansible.builtin.dnf:
    state: present
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
    disable_gpg_check: true

- name: Install ffmpeg Packages
  become: true
  become_user: root
  ansible.builtin.dnf:
    state: present
    name: ffmpeg
    disable_gpg_check: true
    allowerasing: true
