#!/bin/bash

# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

# Resolves the current upstream release of Temurin, Node.js and Go that
# roles/development/tasks/upstream.yml would install, for both amd64 and
# arm64, and pins their checksums into
# roles/development/files/upstream-checksums.yml. upstream.yml refuses to
# install a build that does not match what is pinned there, so this is the
# only supported way to move the pin forward - run it whenever a version in
# roles/development/defaults/main.yml changes, and whenever a playbook run
# fails because upstream shipped a new build under a version that is already
# pinned.
#
# Needs curl and jq.

set -o nounset
set -o errexit
set -o pipefail

cd "$(dirname "$0")/.."

DEFAULTS=roles/development/defaults/main.yml
CHECKSUMS=roles/development/files/upstream-checksums.yml

default_value() {
    grep -oP "^$1:\s*\"?\K[^\"]+" "$DEFAULTS"
}

TEMURIN_MAJOR=$(default_value development_temurin_major)
NODE_MAJOR=$(default_value development_node_major)
GO_VERSION=$(default_value development_go_version)

echo "Pinning Temurin ${TEMURIN_MAJOR}, Node.js ${NODE_MAJOR}.x and Go ${GO_VERSION}" >&2

# --- Temurin ---
# The assets API (rather than the redirect upstream.yml downloads from) is
# what carries a checksum next to the release it belongs to.
temurin_asset() {
    curl --silent --show-error --location \
        "https://api.adoptium.net/v3/assets/latest/${TEMURIN_MAJOR}/hotspot?image_type=jdk&os=linux&architecture=$1" |
        jq '.[0]'
}

TEMURIN_X64=$(temurin_asset x64)
TEMURIN_AARCH64=$(temurin_asset aarch64)

TEMURIN_VERSION_X64=$(jq -r '.release_name' <<<"$TEMURIN_X64")
TEMURIN_VERSION_AARCH64=$(jq -r '.release_name' <<<"$TEMURIN_AARCH64")
if [[ "$TEMURIN_VERSION_X64" != "$TEMURIN_VERSION_AARCH64" ]]; then
    echo "Temurin disagrees on the release between x64 (${TEMURIN_VERSION_X64}) and aarch64 (${TEMURIN_VERSION_AARCH64}), aborting" >&2
    exit 1
fi
TEMURIN_VERSION="$TEMURIN_VERSION_X64"
TEMURIN_SHA_X64=$(jq -r '.binary.package.checksum' <<<"$TEMURIN_X64")
TEMURIN_SHA_AARCH64=$(jq -r '.binary.package.checksum' <<<"$TEMURIN_AARCH64")

# --- Node.js ---
# One checksum file covers every architecture, so it also proves they agree
# on the release.
NODE_SHASUMS=$(curl --silent --show-error --location "https://nodejs.org/dist/latest-v${NODE_MAJOR}.x/SHASUMS256.txt")
NODE_VERSION=$(grep -oP "node-v\K[0-9.]+(?=-linux-x64\.tar\.gz)" <<<"$NODE_SHASUMS")
NODE_SHA_X64=$(grep " node-v${NODE_VERSION}-linux-x64.tar.gz\$" <<<"$NODE_SHASUMS" | cut -d' ' -f1)
NODE_SHA_ARM64=$(grep " node-v${NODE_VERSION}-linux-arm64.tar.gz\$" <<<"$NODE_SHASUMS" | cut -d' ' -f1)

# --- Go ---
GO_INDEX=$(curl --silent --show-error --location "https://go.dev/dl/?mode=json")
GO_RELEASE=$(jq --arg v "$GO_VERSION" '[.[] | select(.version | test("^go" + $v + "(\\.|$)"))][0]' <<<"$GO_INDEX")
GO_VERSION_FULL=$(jq -r '.version' <<<"$GO_RELEASE")
GO_SHA_AMD64=$(jq -r '.files[] | select(.os == "linux" and .arch == "amd64" and .kind == "archive") | .sha256' <<<"$GO_RELEASE")
GO_SHA_ARM64=$(jq -r '.files[] | select(.os == "linux" and .arch == "arm64" and .kind == "archive") | .sha256' <<<"$GO_RELEASE")

for value in "$TEMURIN_VERSION" "$TEMURIN_SHA_X64" "$TEMURIN_SHA_AARCH64" \
    "$NODE_VERSION" "$NODE_SHA_X64" "$NODE_SHA_ARM64" \
    "$GO_VERSION_FULL" "$GO_SHA_AMD64" "$GO_SHA_ARM64"; do
    if [[ -z "$value" || "$value" == "null" ]]; then
        echo "Could not resolve one of the upstream releases, aborting without touching $CHECKSUMS" >&2
        exit 1
    fi
done

cat >"$CHECKSUMS" <<EOF
# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

# Pinned checksums for the tarballs tasks/upstream.yml downloads, keyed by the
# exact upstream version and CPU architecture. Generated by
# scripts/update-upstream-checksums.sh - do not hand-edit.
---
temurin:
  version: $TEMURIN_VERSION
  x64: $TEMURIN_SHA_X64
  aarch64: $TEMURIN_SHA_AARCH64
node:
  version: $NODE_VERSION
  x64: $NODE_SHA_X64
  arm64: $NODE_SHA_ARM64
go:
  version: $GO_VERSION_FULL
  amd64: $GO_SHA_AMD64
  arm64: $GO_SHA_ARM64
EOF

echo "Wrote $CHECKSUMS" >&2
echo "  Temurin ${TEMURIN_VERSION}" >&2
echo "  Node.js ${NODE_VERSION}" >&2
echo "  Go ${GO_VERSION_FULL}" >&2
