---
# vars file for rust
# https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
rustup_init_url: '{{ rustup_mirror }}/{{ rustup_platform }}/rustup-init'
rustup_platform: '{{ ansible_architecture }}-unknown-{{ rustup_os_map[ansible_system] }}'
rustup_exe: '{{ rustup_install_dir }}/rustup-init'
rustup_init_cmd: >-
  {{ rustup_exe }}
  --profile {{ rustup_profile | default("default") | quote }}
  -y
