# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
# Install Docker from the official repos
# References:
# https://docs.docker.com/engine/install/ubuntu/
# https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/setup-Debian.yml

- name: Uninstall old versions
  ansible.builtin.apt:
    state: absent
    name: "{{ item }}"
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
  become: true

- name: Set up the repository
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  become: true

- name: Add Docker apt key
  ansible.builtin.shell: |
    set -o pipefail
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    executable: /bin/bash
  changed_when: false
  become: true

# Special handling because Docker provides no packages for Ubuntu's development branch
- name: Get Ubuntu codename
  ansible.builtin.set_fact:
    deb_release_codename: "{{ 'jammy' if ansible_lsb.description is search('development branch', ignorecase=True) else ansible_distribution_release }}"
  when: ansible_distribution == 'Ubuntu'

# Special handling because Docker provides no packages for Debian Trixie as of now
- name: Get Debian codename
  ansible.builtin.set_fact:
    deb_release_codename: "{{ 'bookworm' if ansible_lsb.description is search('sid', ignorecase=True) else ansible_distribution_release }}"
  when: ansible_distribution == 'Debian'

- name: dbg
  ansible.builtin.debug:
    msg: |
      Debian codename for Docker apt repo: {{ deb_release_codename }}
      Actual ansible_distribution_release: {{ ansible_distribution_release }} ({{ ansible_lsb.description }})
      Ansible Distribution: {{ansible_distribution|lower}}

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ansible_distribution|lower}}   {{ deb_release_codename }} stable"
    state: present
    update_cache: true
  become: true

- name: Install Docker Engine
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true

- name: Start and enable the docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750
  become: true

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  become: true

- name: Install podman
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - podman
  become: true
  # TODO: Update once focal is not required anymore
  when: ansible_distribution_release != "focal"
