# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
# See:
# https://fedoramagazine.org/docker-and-fedora-35/

- name: Make sure podman-docker is not installed because it conflicts with docker
  ansible.builtin.dnf:
    state: absent
    name: podman-docker

- name: Install the docker packages
  ansible.builtin.dnf:
    state: present
    name:
      - moby-engine
      - docker-compose

- name: Start and enable the docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
