# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT

---
# See:
# https://fedoramagazine.org/docker-and-fedora-35/

- name: Make sure podman-docker is not installed because it conflicts with docker
  ansible.builtin.dnf:
    state: absent
    name: podman-docker
  become: true

- name: Install the docker packages
  ansible.builtin.dnf:
    state: present
    name: "{{ item }}"
  loop:
    - moby-engine
    - docker-compose
  become: true

- name: Start and enable the docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750
  become: true

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  become: true
