---

# See:
# https://fedoramagazine.org/docker-and-fedora-35/

- name: Make sure podman-docker is not installed because it conflicts with docker
  dnf:
    state: absent
    name: podman-docker
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install the docker packages
  dnf:
    state: present
    name: "{{ item }}"
  loop:
    - moby-engine
    - docker-compose
  become: true
  when: ansible_os_family == 'RedHat'

- name: Start and enable the docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750
  become: true
  when: ansible_os_family == 'RedHat'

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: yes
  become: true
  when: ansible_os_family == 'RedHat'
