---
# Install Docker from the official repos
# References:
# https://docs.docker.com/engine/install/ubuntu/
# https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/setup-Debian.yml

- name: Uninstall old versions
  ansible.builtin.apt:
    state: absent
    name: "{{ item }}"
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
  become: true

- name: Set up the repository
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  become: true

- name: Add Docker apt key
  ansible.builtin.shell: |
    set -o pipefail
    curl -sSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    executable: /bin/bash
  changed_when: false
  become: true

# Special handling because Docker provides no packages for Ubuntu's development branch
- name: Get Ubuntu codename
  ansible.builtin.set_fact:
    ubuntu_codename: "{{ 'jammy' if ansible_lsb.description is search('development branch', ignorecase=True) else ansible_distribution_release }}"

- name: dbg
  ansible.builtin.debug:
    msg: |
      Ubuntu codename for Docker apt repo: {{ ubuntu_codename }}
      Actual ansible_distribution: {{ ansible_distribution_release }} ({{ ansible_lsb.description }})

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu   {{ ubuntu_codename }} stable"
    state: present
    update_cache: true
  become: true

- name: Install Docker Engine
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true

- name: Start and enable the docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750
  become: true

- name: Add user to group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  become: true

- name: Install podman
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - podman
  become: true
  # TODO: Update once focal is not required anymore
  when: ansible_distribution_release != "focal"
