# SPDX-FileCopyrightText: iesplin
# SPDX-License-Identifier: MIT

---
- name: Install Debian dependencies
  apt:
    name:
      - apt-transport-https
      - gpg
    state: present
    update_cache: true

- name: Add Microsoft repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/vscode"
    suites: stable
    components: [main]
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    enabled: true
