# SPDX-FileCopyrightText: iesplin
# SPDX-License-Identifier: MIT

---
- name: Install Debian dependencies
  apt:
    name:
      - apt-transport-https
      - gpg
      - curl
    state: present
    update_cache: true

- name: Add Microsoft signing key
  ansible.builtin.shell: |
    set -o pipefail
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc -o /etc/apt/keyrings/microsoft.asc
    chmod a+r /etc/apt/keyrings/microsoft.asc
  args:
    executable: /bin/bash
  changed_when: false
  become: true

- name: Add Microsoft repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
