---
# tasks file for ansible-role-codium
- name: Ensure GPG key for repo is installed (RedHat)
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    fingerprint: "{{ gpg_fingerprint }}"
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure repo is installed (RedHat)
  ansible.builtin.yum_repository:
    name: codium
    description: gitlab.com_paulcarroty_vscodium_repo
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    enabled: true
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: true
    repo_gpgcheck: true
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure GPG key for repo is installed (Debian)
  ansible.builtin.apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    id: "{{ gpg_fingerprint }}"
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: Ensure repo is installed (Debian)
  ansible.builtin.apt_repository:
    repo: "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main"
    filename: codium
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'Debian'

- name: Ensure codium is installed
  ansible.builtin.package:
    name: codium
    state: present
