# SPDX-FileCopyrightText: Sion Fandrick
# SPDX-License-Identifier: MIT

---
# tasks file for ansible-role-codium
- name: Ensure GPG key for repo is installed (RedHat/Suse)
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    fingerprint: "{{ gpg_fingerprint }}"
  when:
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Suse'

- name: Ensure repo is installed (RedHat)
  ansible.builtin.yum_repository:
    name: codium
    description: gitlab.com_paulcarroty_vscodium_repo
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    enabled: true
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: true
    repo_gpgcheck: true
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure repo is installed (Debian)
  ansible.builtin.deb822_repository:
    name: codium
    types: [deb]
    uris: "https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/"
    suites: vscodium
    components: [main]
    signed_by: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present
    enabled: true
  when:
    - ansible_os_family == 'Debian'

- name: Add VSCodium repo file
  ansible.builtin.copy:
    dest: /etc/zypp/repos.d/vscodium.repo
    content: |
      [gitlab.com_paulcarroty_vscodium_repo]
      name=gitlab.com_paulcarroty_vscodium_repo
      baseurl=https://download.vscodium.com/rpms/
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
      metadata_expire=1h
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_os_family == 'Suse'

- name: Ensure codium is installed
  ansible.builtin.package:
    name: codium
    state: present
    update_cache: yes
