# SPDX-FileCopyrightText: 2022 Maxwell G <gotmax@e.email>
# SPDX-License-Identifier: Unlicense
---
- name: Enable CRB
  hosts: all
  become: true
  tasks:
    - name: Enable CRB
      when:
        - "ansible_os_family == 'RedHat'"
        - "ansible_distribution != 'Fedora'"
      ansible.builtin.include_role:
        name: gotmax23.epel.crb
