Vagrant.configure(2) do |config|
  config.vm.box = "debian/testing64"

  config.vm.provider 'libvirt' do |provider|
    provider.memory = 1024
    provider.cpus = 2
  end

  config.vm.provider "virtualbox" do |provider|
    provider.memory = 1024
    provider.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../dev.yml"
      ansible.raw_arguments = [
          '--verbose'
      ]
  end
end
