# SPDX-FileCopyrightText: Florian Wilhelm
# SPDX-License-Identifier: MIT
# Based on an example from https://lima-vm.io/docs/examples/gha/

name: CI with Lima VM

on:
  workflow_dispatch:

jobs:
  lima:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        distro: [fedora, debian]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: "Set up Lima"
        uses: lima-vm/lima-actions/setup@v1
        id: lima-actions-setup

      - name: "Cache ~/.cache/lima"
        uses: actions/cache@v4
        with:
          path: ~/.cache/lima
          key: lima-${{ steps.lima-actions-setup.outputs.version }}

      - name: "Start an instance of ${{ matrix.distro }}"
        run: |
          set -eux

          cat lima_${{ matrix.distro }}.yaml | limactl create --name=default -
          limactl start 
          lima ansible-playbook --inventory inventory common.yml
